apiVersion: v1
kind: Service
metadata:
  name: details-k8-service
  namespace: frontendapp
spec:
  type: LoadBalancer
  selector:
    app: details
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
